server:
  port: 8081
spring:
  application:
    name: answerService
  datasource:
    url: jdbc:mysql://120.25.192.9:3306/cloud0?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cloud0
    password: cloud0
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
#eureka:
#  client:
#    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
#    service-url:
#      defaultZone: http://localhost:8888/eureka