server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://120.25.192.9:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cloud
    password: cloud